# Generated by Django 6.0.5 on 2026-06-20 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kichwa')),
                ('description', models.TextField(verbose_name='Maelezo')),
                ('category', models.CharField(choices=[('phishing', 'Ulaghai wa Barua Pepe'), ('ransomware', 'Mashambulizi ya Ransomware'), ('unauthorized', 'Upatikanaji Bila Idhini'), ('malware', 'Virusi / Malware'), ('ddos', 'Mashambulizi ya DDoS'), ('insider', 'Tishio la Ndani'), ('data_breach', 'Uvujaji wa Data'), ('other', 'Nyingine')], max_length=20, verbose_name='Aina')),
                ('status', models.CharField(choices=[('open', 'Wazi / Mpya'), ('investigating', 'Inachunguzwa'), ('contained', 'Imezuiliwa'), ('resolved', 'Imetatuliwa'), ('closed', 'Imefungwa')], default='open', max_length=20, verbose_name='Hali')),
                ('priority', models.CharField(choices=[('low', 'Ya Chini'), ('medium', 'Ya Kati'), ('high', 'Ya Juu'), ('critical', 'Muhimu Sana')], default='medium', max_length=10, verbose_name='Kiwango')),
                ('affected_systems', models.TextField(blank=True, null=True, verbose_name='Mifumo Iliyoathirika')),
                ('impact_description', models.TextField(blank=True, null=True, verbose_name='Athari')),
                ('root_cause', models.TextField(blank=True, null=True, verbose_name='Chanzo')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarehe ya Kuripoti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tarehe ya Sasisho')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tarehe ya Kutatuliwa')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Siri')),
                ('is_escalated', models.BooleanField(default=False, verbose_name='Imepelekwa Juu')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Imepewa')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Mripoti')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Ukubwa wa faili katika bytes')),
                ('file_type', models.CharField(help_text='Aina ya faili', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cyberincident.incident')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Mfanyakazi'), ('ict', 'Mchambuzi wa ICT'), ('admin', 'Msimamizi')], default='staff', max_length=20)),
                ('hospital_id', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('investigation', 'Uchunguzi'), ('containment', 'Uzuiaji'), ('eradication', 'Kuondoa Tishio'), ('recovery', 'Kurejesha Mifumo'), ('notification', 'Arifu kwa Wadau'), ('reporting', 'Kuripoti kwa Mamlaka'), ('patch', 'Kusasisha Programu'), ('backup', 'Kurejesha Backup'), ('training', 'Mafunzo kwa Wafanyakazi'), ('other', 'Nyingine')], max_length=20)),
                ('action_text', models.TextField(help_text='Maelezo ya hatua iliyochukuliwa')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Maelezo ya ziada', null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='cyberincident.incident')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
